package com.ezworking.wechatunlock.domain;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ezworking.wechatunlock.domain.ContactResult;

import com.ezworking.wechatunlock.domain.ContactResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactResultDaoConfig;

    private final ContactResultDao contactResultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactResultDaoConfig = daoConfigMap.get(ContactResultDao.class).clone();
        contactResultDaoConfig.initIdentityScope(type);

        contactResultDao = new ContactResultDao(contactResultDaoConfig, this);

        registerDao(ContactResult.class, contactResultDao);
    }
    
    public void clear() {
        contactResultDaoConfig.getIdentityScope().clear();
    }

    public ContactResultDao getContactResultDao() {
        return contactResultDao;
    }

}
